version: '3'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: userdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "20106:3306"
    volumes:
      - db_data:/var/lib/mysql  # Bind the volume to MySQL's data directory

volumes:
  db_data:
